version: '3.3'

services:
  wordpress:
    container_name: wordpress
    depends_on:
      - db
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./site:/var/www/html
    ports:
      - '80:80'
    restart: always
    environment:
      WORDPRESS_DB_HOST: $DB_HOST
      WORDPRESS_DB_USER: $DB_USER
      WORDPRESS_DB_PASSWORD: $DB_PASSWORD
      WORDPRESS_TABLE_PREFIX: $DB_TABLE_PREFIX
      WORDPRESS_DEBUG: $WP_DEBUG_MODE
      DISABLED_PLUGINS: $WP_DISABLE_PLUGINS
  db:
    container_name: db
    image: mysql:5.7
    volumes:
      - ./database:/var/lib/mysql
      - ./mysqldumps/backup.sql.gz:/docker-entrypoint-initdb.d/backup.sql.gz
      - ./init/migrate.sh:/docker-entrypoint-initdb.d/migrate.sh
    restart: always
    ports: 
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: $db_root_password
      MYSQL_DATABASE: $db_name
      MYSQL_USER: $db_user
      MYSQL_PASSWORD: $db_password
      WORDPRESS_TABLE_PREFIX: $db_table_prefix
      PRODUCTION_URL: $production_url
  
  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - '8080:8080'
