version: '3.3'

services:
  wordpress:
    container_name: wordpress
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./site:/var/www/html
    ports:
      - '${WP_PORT}:80'
    restart: always
    environment:
      WORDPRESS_DB_HOST: $DB_HOST
      WORDPRESS_DB_USER: $DB_USER
      WORDPRESS_DB_PASSWORD: $DB_PASSWORD
      WORDPRESS_TABLE_PREFIX: $DB_TABLE_PREFIX
      WORDPRESS_DEBUG: $WP_DEBUG_MODE
      DISABLED_PLUGINS: $WP_DISABLE_PLUGINS
  db:
    container_name: wordpress_mysql
    image: mysql:5.7
    volumes:
      - ./database:/var/lib/mysql
      - ./mysqldumps/backup.sql.gz:/docker-entrypoint-initdb.d/backup.sql.gz
      - ./init/migrate.sh:/docker-entrypoint-initdb.d/migrate.sh
    restart: always
    ports: 
      - '${MYSQL_PORT}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD
      MYSQL_DATABASE: $DB_NAME
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASSWORD
      WORDPRESS_TABLE_PREFIX: $DB_TABLE_PREFIX
      PRODUCTION_URL: $PRODUCTION_URL
  
  adminer:
    container_name: wordpress_adminer
    image: adminer
    restart: always
    ports:
      - '${ADMINER_PORT}:8080'
