version: '3.3'

services:
  wordpress:
    container_name: $PROJECT_NAME-wordpress
    depends_on:
      - mysql
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./site/$PROJECT_NAME:/var/www/html
    ports:
      - '${WORDPRESS_PORT}:80'
    restart: always
    environment:
      WORDPRESS_DB_HOST: $WORDPRESS_DB_HOST
      WORDPRESS_DB_USER: $WORDPRESS_DB_USER
      WORDPRESS_DB_PASSWORD: $WORDPRESS_DB_PASSWORD
      WORDPRESS_TABLE_PREFIX: $WORDPRESS_DB_TABLE_PREFIX
      WORDPRESS_DEBUG: $WORDPRESS_DEBUG
      DISABLED_PLUGINS: $WORDPRESS_DISABLE_PLUGINS
  mysql:
    container_name: $PROJECT_NAME-mysql
    image: mysql:5.7
    volumes:
      - ./database:/var/lib/mysql
      - ./mysqldumps/backup.sql.gz:/docker-entrypoint-initdb.d/backup.sql.gz
      - ./init/migrate.sh:/docker-entrypoint-initdb.d/migrate.sh
    restart: always
    ports: 
      - '${MYSQL_PORT}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: $WORDPRESS_DB_ROOT_PASSWORD
      MYSQL_DATABASE: $WORDPRESS_DB_NAME
      MYSQL_USER: $WORDPRESS_DB_USER
      MYSQL_PASSWORD: $WORDPRESS_DB_PASSWORD
      WORDPRESS_TABLE_PREFIX: $WORDPRESS_DB_TABLE_PREFIX
      PRODUCTION_URL: $PRODUCTION_URL
  
  adminer:
    container_name: wordpress_adminer
    image: adminer
    restart: always
    ports:
      - '${ADMINER_PORT}:8080'
